1. Crear un vector con valores dentro del rango 10 a 49


In [1]:
import numpy as np
from scipy import stats

In [2]:
a= np.array ([11,15,23,25])

In [3]:
a

array([11, 15, 23, 25])

In [4]:
np.arange(10, 49, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

2.Invertir el vector creado en el ejercicio 1.

In [5]:
np.flip(a)

array([25, 23, 15, 11])

In [6]:
a[::-1]

array([25, 23, 15, 11])

3 .Crear una matriz de 3x3 con los valores de 0 a 8.

In [7]:
b=([0,1,2],[3,4,5],[6,7,8])

In [8]:
b

([0, 1, 2], [3, 4, 5], [6, 7, 8])

In [9]:
print(b)

([0, 1, 2], [3, 4, 5], [6, 7, 8])


In [10]:
np.shape(b)

(3, 3)

4. Encontrar los índices que no son ceros del arreglo
[1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0].

In [11]:
c=np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])

In [12]:
np.where(c != 0)[0]

array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14])

5. Crear una matriz identidad de 6x6.

In [13]:
identity=np.identity(6)

In [14]:
identity

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

6. Encontrar los índices de los valores mínimos y máximos de la matriz creada en
el ejercicio 3.

In [15]:
np.argmax(b)

8

In [16]:
np.argmin(b)


0

7. Crear una matriz de 10x10 con 1 en los bordes y 0 en el interior (con rangos de
índices).

In [17]:
d=np.ones((10,10))

In [18]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [19]:
d[1:9,1:9]=0

In [20]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

8. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4

In [21]:
np.full((5,5),(0,1,2,3,4))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [22]:
matrix=np.ones((5,5))

In [23]:
matrix

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
matrix[:,:]=[0,1,2,3,4]

In [25]:
matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [66]:
arr = np.array([[0,1,2,3,4]])
m1=np.repeat(arr,5, axis=0)
m1

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

9. Crear dos arreglos al azar A y B, verificar si son iguales.

In [26]:
a=np.array([2,6,7,8,9,9])

In [27]:
b=np.array([20,33,566,88,6,0])

In [28]:
np.equal(a,b)

array([False, False, False, False, False, False])

10.Crear una matriz de 20x20 de valores aleatorios entre 1 y 100, luego indicar su
media, su mediana, su moda y el desvío estándar. Los valores que den como
resultado flotantes deben tener como máximo 2 decimales.

In [29]:
mr=np.random.randint(1,100, size=(20,20))

In [30]:
mr

array([[66, 13,  4, 92, 99, 57, 25, 69, 53, 45, 47,  3, 69, 44, 65,  8,
        58, 67, 95, 61],
       [24, 19, 36, 18, 23, 80, 63,  3, 95, 18, 30, 53, 28,  7, 32, 87,
        44, 89,  3, 85],
       [85, 78, 82, 69, 47,  3, 60, 71, 72, 62, 46, 85,  6, 36, 79, 71,
        20, 29, 82, 83],
       [52, 76, 23, 56, 42, 57, 53,  3, 77, 35, 26, 86, 76, 85, 69, 80,
        53, 62, 54, 73],
       [86, 47, 91, 30, 38, 26,  7, 37, 55, 41, 24, 78, 31, 22, 10, 61,
        27, 25, 34, 98],
       [91, 85, 25, 25, 48, 54, 19, 44, 47, 59, 91, 79,  5, 88, 19, 20,
         6, 24, 88, 68],
       [68, 39, 14, 48, 96, 70, 68, 49, 33, 36, 17, 74, 41, 78, 55, 44,
        31, 97, 26, 21],
       [28, 39,  5, 35, 94, 69, 89, 72, 76, 38, 77, 59, 11, 43, 32, 49,
        29, 58, 93,  2],
       [87, 33, 85, 16, 70, 63, 52, 89,  1,  2, 88, 94, 36, 58, 53, 26,
        54, 12, 45, 25],
       [81, 15, 46, 82, 16,  2, 99, 28, 62, 26, 64, 80, 51, 63,  2, 99,
        83, 72, 28, 16],
       [82, 18, 86, 46, 64, 51

In [31]:
np.mean(mr)

50.6725

In [32]:
np.median(mr)

52.0

In [33]:
mode = stats.mode(mr)


In [34]:
print(mode[0])

[[66 39 67  4  3 57 19  3 72 92 17 79 11 88 32 99 29 14 26 21]]


In [35]:
np.std(mr)

28.129437316626156

11.Crear dos arreglos de 4 elementos enteros y hacer las siguientes operaciones:
sumarlos, restarle el segundo al primero, multiplicarlos, dividir el primero por el
segundo. Hacerlo utilizando métodos.

In [36]:
v1= np.array([2,6,8,9])

In [37]:
v1

array([2, 6, 8, 9])

In [38]:
v2=np.array([10,15,34,39])

In [39]:
v2

array([10, 15, 34, 39])

In [40]:
np.add(v1,v2)

array([12, 21, 42, 48])

In [41]:
np.subtract(v1,v2)

array([ -8,  -9, -26, -30])

In [42]:
np.multiply(v1,v2)

array([ 20,  90, 272, 351])

In [43]:
np.divide(v1,v2)

array([0.2       , 0.4       , 0.23529412, 0.23076923])

12.Crear una matriz de 4x4 de valores aleatorios entre 1 y 10, y luego agregarle
una fila de 0s al final.

In [44]:
m5=np.random.randint(1,10, size=(4,4))

In [45]:
m5

array([[2, 4, 5, 5],
       [8, 6, 7, 4],
       [5, 4, 9, 7],
       [6, 6, 6, 4]])

In [46]:
m5[3:,::]=0

In [47]:
m5

array([[2, 4, 5, 5],
       [8, 6, 7, 4],
       [5, 4, 9, 7],
       [0, 0, 0, 0]])

13.Crear dos arreglos de 6 elementos de valores aleatorios entre 0 y 1 y luego
realizar las operaciones lógicas and y or con los métodos de NumPy.

In [48]:
m6=np.random.rand(6)

In [49]:
m6

array([0.86734405, 0.99321616, 0.89170858, 0.10055365, 0.09776148,
       0.24362231])

In [50]:
m7=np.random.rand(6)

In [51]:
m7

array([6.94859911e-01, 3.89690147e-01, 3.84575051e-01, 6.49090181e-04,
       9.13327423e-01, 2.55061620e-02])

In [52]:
np.logical_and(m6,m7)

array([ True,  True,  True,  True,  True,  True])

In [53]:
np.logical_or(m6,m7)

array([ True,  True,  True,  True,  True,  True])

14.Crear un arreglo de 4 elementos de entre 0 y 10, informar la cantidad de
elementos que tiene y también cuántos bytes ocupa el arreglo.

In [54]:
m5=np.random.randint(10, size=4)

In [55]:
m5

array([2, 1, 8, 6])

In [56]:
np.size(m5)

4

In [57]:
np.array(m5).itemsize

8

In [58]:
np.array(m5).nbytes

32

15.Crear una matriz que contenga información en distintos formatos, imprimir la info
de cada formato a través del atributo.